export const jokes = [
    "Yo mama so old, her social security number is 1.",
    "Yo mama so poor, ducks throw bread at her.",
    "Yo mama so fat, when she skips a meal, the stock market drops.",
    "Yo mama so hairy, Bigfoot took her picture.",
    "Yo mama so clumsy, she tripped over a wireless connection.",
    "Yo mama so dumb, she tried to climb Mountain Dew.",
    "Yo mama so lazy, she has a stay-at-home job and still calls in sick.",
    "Yo mama so short, you can see her feet on her driver’s license photo.",
    "Yo mama so tall, she did a backflip and kicked the moon.",
    "Yo mama so old, her birth certificate says 'Expired.'",
    "Yo mama so fat, when she wears high heels, she strikes oil.",
    "Yo mama so slow, it took her two hours to watch *60 Minutes*.",
    "Yo mama so big, when she goes camping, the bears hide their food.",
    "Yo mama so scary, even Scooby-Doo won’t investigate her house.",
    "Yo mama so greasy, her face could fry a turkey.",
    "Yo mama so bald, when she wears a turtleneck, she looks like a roll-on deodorant.",
    "Yo mama so silly, she thought a quarterback was a refund.",
    "Yo mama so fat, she sat on an iPhone and turned it into an iPad.",
    "Yo mama so annoying, she makes onions cry.",
    "Yo mama so broke, she goes to KFC to lick other people’s fingers.",
    "Yo mama so dirty, she makes garbage look clean.",
    "Yo mama so short, she poses for trophies.",
    "Yo mama so sweet, Willy Wonka tried to buy her.",
    "Yo mama so fat, she uses Google Earth to take selfies.",
    "Yo mama so dense, light bends around her.",
    "Yo mama so cold, when she walks into a room, it snows.",
    "Yo mama so loud, she can wake the dead with a whisper.",
    "Yo mama so long-winded, she could narrate a silent film.",
    "Yo mama so unlucky, she got hit by a parked car.",
    "Yo mama so old, her memory is in black and white.",
    "Yo mama so fat, her blood type is Nutella.",
    "Yo mama so clumsy, she tripped over a shadow.",
    "Yo mama so blind, she bought a donut and tried to play it on her record player.",
    "Yo mama so confusing, GPS can't find her logic.",
    "Yo mama so weird, aliens refuse to abduct her.",
    "Yo mama so dramatic, she cries during commercials.",
    "Yo mama so hot, the sun wears sunscreen around her.",
    "Yo mama so cold-hearted, she uses liquid nitrogen as moisturizer.",
    "Yo mama so loud, her whisper registered on the Richter scale.",
    "Yo mama so unlucky, she got hit by a falling star.",
    "Yo mama so fake, Barbie looks real next to her.",
    "Yo mama so lazy, she dreams of napping.",
    "Yo mama so clueless, she stared at a cup of orange juice for 12 hours because it said 'concentrate.'",
    "Yo mama so weird, even Google can’t understand her search history.",
    "Yo mama so flat, she can hang glide on a Dorito.",
    "Yo mama so bold, she flosses with a jump rope.",
    "Yo mama so pale, she blends into a snowstorm.",
    "Yo mama so fat, she uses a mattress as a tampon.",
    "Yo mama so mean, she makes Voldemort look like Mr. Rogers.",
    "Yo mama so tiny, she uses a thimble as a jacuzzi.",
    "Yo mama so bright, her brain should be on airplane mode.",
    "Yo mama so slow, she missed a snail race and came in last.",
    "Yo mama so fancy, she wears diamonds to Walmart.",
    "Yo mama so crusty, bread asks her for a bath.",
    "Yo mama so stinky, her deodorant gave up.",
    "Yo mama so cold, when she breathes, icicles form.",
    "Yo mama so tense, she snapped a yoga mat.",
    "Yo mama so delusional, she tried to high-five her reflection.",
    "Yo mama so paranoid, she puts passwords on her cereal box.",
    "Yo mama so bad at tech, she thought TikTok was a clock app.",
    "Yo mama so cheap, she brings her own ketchup to McDonald’s.",
    "Yo mama so forgetful, she rebooted the microwave.",
    "Yo mama so slow, she took a nap on a treadmill.",
    "Yo mama so cheesy, mice follow her everywhere.",
    "Yo mama so sleepy, even coffee gives up on her.",
    "Yo mama so dense, black holes orbit her.",
    "Yo mama so emo, she cuts onions to feel better.",
    "Yo mama so robotic, Alexa asks her for advice.",
    "Yo mama so watery, she cries during action movies.",
    "Yo mama so unlucky, she plays solitaire and loses.",
    "Yo mama so nerdy, she cosplays as a calculator.",
    "Yo mama so invisible, even her shadow left.",
    "Yo mama so awkward, she high-fives herself and misses.",
    "Yo mama so plain, toast finds her boring.",
    "Yo mama so weird, her echo won’t talk back.",
    "Yo mama so spacey, NASA keeps trying to contact her.",
    "Yo mama so rubbery, she bounces when she trips.",
    "Yo mama so neon, she glows in daylight.",
    "Yo mama so spicy, jalapeños call her boss.",
    "Yo mama so bitter, lemons ask for sugar.",
    "Yo mama so dramatic, her sneeze deserves an Oscar.",
    "Yo mama so shy, shadows avoid her.",
    "Yo mama so flat, the pancake called her 3D.",
    "Yo mama so hollow, she echoes when she talks.",
    "Yo mama so crispy, KFC tried to hire her.",
    "Yo mama so crunchy, granola avoids her.",
    "Yo mama so heavy, Thanos needed two snaps.",
    "Yo mama so hyper, caffeine drinks her.",
    "Yo mama so quiet, librarians ask her to speak up.",
    "Yo mama so old, she babysat Yoda.",
    "Yo mama so dramatic, she auditioned for a soap commercial and cried.",
    "Yo mama so bold, she microwaves metal.",
    "Yo mama so long, she can tie her shoes standing up.",
    "Yo mama so inflated, balloons get jealous.",
    "Yo mama so stylish, mannequins take notes.",
    "Yo mama so backwards, her GPS says 'You're lost.'",
    "Yo mama so confusing, IKEA instructions make more sense.",
    "Yo mama so offbeat, metronomes skip her.",
    "Yo mama so basic, she orders water at Starbucks.",
    "Yo mama so sweet, bees follow her around.",
];
